// frontend/src/app/pages/user/budgets.component.ts
import { Component, computed, effect, inject, signal, untracked } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { debounceTime } from 'rxjs';
import { ApiService } from '../../core/api.service';
import { errorMessage } from '../../core/auth.interceptor';
import { AuthService } from '../../core/auth.service';
import { Budget, Category } from '../../core/models';
import { RealtimeService } from '../../core/realtime.service';
import { Months, ToastService } from '../../core/ui.service';
import { ConfirmComponent, ModalComponent } from '../../shared/modal.component';
import { MonthPickerComponent } from '../../shared/month-picker.component';
import { MoneyPipe } from '../../shared/pipes';
import { CategoryNamePipe, I18nService, t, TranslatePipe } from '../../core/i18n';

@Component({
  selector: 'app-budgets',
  imports: [ReactiveFormsModule, MonthPickerComponent, MoneyPipe, ModalComponent, ConfirmComponent, TranslatePipe, CategoryNamePipe],
  template: `
    <div class="page">
      <div class="page-header">
        <div>
          <h1>{{ 'budgets.title' | t }}</h1>
          <p>{{ 'budgets.subtitle' | t }}</p>
        </div>
        <div class="header-actions">
          <app-month-picker [(month)]="month" />
          <button class="btn btn-ghost" (click)="copyPrevious()">⧉ {{ 'budgets.copy' | t }}</button>
          <button class="btn btn-primary" (click)="open(null)">＋ {{ 'budgets.new' | t }}</button>
        </div>
      </div>

      @if (overall(); as o) {
        <div class="card overall">
          <div class="row-between">
            <div>
              <div class="muted small">{{ 'budgets.overallTitle' | t }}</div>
              <div class="big">{{ o.spent | money: cur() }} <span class="muted">/ {{ o.limitAmount | money: cur() }}</span></div>
            </div>
            <div class="ring" [style.--p]="o.percent > 100 ? 100 : o.percent" [style.--c]="color(o.percent)"><span>{{ o.percent }}%</span></div>
          </div>
          <div class="progress lg"><div [style.width.%]="o.percent > 100 ? 100 : o.percent" [style.background]="color(o.percent)"></div></div>
          <div class="row-between small">
            <span [class]="o.remaining < 0 ? 'text-danger' : 'muted'">{{ (o.remaining < 0 ? 'budgets.overBy' : 'budgets.remaining') | t: { amount: (abs(o.remaining) | money: cur()) } }}</span>
            <span>
              <button class="icon-btn" [title]="'common.edit' | t" (click)="open(o)">✏️</button>
              <button class="icon-btn danger" [title]="'common.delete' | t" (click)="toDelete.set(o)">🗑️</button>
            </span>
          </div>
        </div>
      }

      <div class="grid grid-3 mt">
        @for (b of categoryBudgets(); track b.id) {
          <div class="card budget" [class.over]="b.percent >= 100">
            <div class="row-between">
              <span class="cat-chip"><span class="cat-dot" [style.background]="b.category!.color + '22'">{{ b.category!.icon }}</span><b>{{ b.category!.name | cat }}</b></span>
              <span class="badge" [class.badge-danger]="b.percent >= 100" [class.badge-warning]="b.percent >= 80 && b.percent < 100" [class.badge-success]="b.percent < 80">{{ b.percent }}%</span>
            </div>
            <div class="amounts"><b>{{ b.spent | money: cur() }}</b> <span class="muted">{{ 'budgets.of' | t: { amount: (b.limitAmount | money: cur()) } }}</span></div>
            <div class="progress"><div [style.width.%]="b.percent > 100 ? 100 : b.percent" [style.background]="color(b.percent)"></div></div>
            <div class="row-between small foot">
              <span [class]="b.remaining < 0 ? 'text-danger' : 'muted'">{{ (b.remaining < 0 ? 'budgets.overBy' : 'budgets.left') | t: { amount: (abs(b.remaining) | money: cur()) } }}</span>
              <span>
                <button class="icon-btn" [title]="'common.edit' | t" (click)="open(b)">✏️</button>
                <button class="icon-btn danger" [title]="'common.delete' | t" (click)="toDelete.set(b)">🗑️</button>
              </span>
            </div>
          </div>
        }
      </div>

      @if (!budgets().length) {
        <div class="card empty-state">
          <div class="emoji">🎯</div>
          <h4>{{ 'budgets.none' | t: { month: monthLabel() } }}</h4>
          <p>{{ 'budgets.noneHint' | t }}</p>
          <button class="btn btn-primary mt" (click)="open(null)">{{ 'budgets.create' | t }}</button>
        </div>
      }
    </div>

    @if (formOpen()) {
      <app-modal [title]="(editing() ? 'budgets.editTitle' : 'budgets.new') | t" (closed)="formOpen.set(false)">
        <form [formGroup]="form" (ngSubmit)="save()">
          <div class="form-field">
            <label>{{ 'common.category' | t }}</label>
            <select class="input" formControlName="categoryId">
              <option [ngValue]="null">🧾 {{ 'budgets.overallChip' | t }}</option>
              @for (c of categories(); track c.id) { <option [ngValue]="c.id">{{ c.icon }} {{ c.name | cat }}</option> }
            </select>
          </div>
          <div class="form-field">
            <label>{{ 'budgets.limit' | t: { cur: cur() } }}</label>
            <input class="input" type="number" step="0.01" formControlName="limitAmount" [placeholder]="'budgets.limitPlaceholder' | t" />
          </div>
          <p class="muted small">{{ 'budgets.appliesTo' | t: { month: monthLabel() } }}</p>
          <div class="modal-actions">
            <button type="button" class="btn btn-ghost" (click)="formOpen.set(false)">{{ 'common.cancel' | t }}</button>
            <button class="btn btn-primary" [disabled]="form.invalid">{{ 'budgets.saveBtn' | t }}</button>
          </div>
        </form>
      </app-modal>
    }
    @if (toDelete(); as b) {
      <app-confirm [title]="'budgets.deleteTitle' | t" [message]="'budgets.deleteMsg' | t: { name: b.category ? (b.category.name | cat) : ('budgets.overallName' | t) }" [confirmLabel]="'common.delete' | t"
                   (confirm)="remove(b)" (cancel)="toDelete.set(null)" />
    }
  `,
  styles: [`
    .overall { display: grid; gap: 14px; background-image: var(--gradient-soft); }
    .big { font-family: var(--font-display); font-size: 28px; font-weight: 700; letter-spacing: -.02em; margin-top: 4px; }
    .big .muted { font-size: 16px; font-weight: 500; }
    .progress.lg { height: 12px; }
    .ring { --p: 0; width: 76px; height: 76px; border-radius: 50%; display: grid; place-items: center;
      background: conic-gradient(var(--c) calc(var(--p) * 1%), var(--surface-3) 0); filter: drop-shadow(0 0 10px var(--c)); }
    .ring span { width: 60px; height: 60px; border-radius: 50%; background: var(--surface-solid); display: grid; place-items: center; font-weight: 700; font-family: var(--font-display); }
    .budget { display: grid; gap: 10px; transition: transform .15s; }
    .budget:hover { transform: translateY(-2px); }
    .budget.over { border-color: color-mix(in srgb, var(--danger) 45%, var(--border)); }
    .amounts { font-size: 18px; }
    .amounts .muted { font-size: 14px; margin-inline-start: 6px; }
    .big .muted { margin-inline-start: 6px; }
    .foot { margin-top: -4px; }
  `],
})
export class BudgetsComponent {
  private api = inject(ApiService);
  private toast = inject(ToastService);
  private fb = inject(FormBuilder);
  private auth = inject(AuthService);

  readonly month = signal(Months.current());
  readonly budgets = signal<Budget[]>([]);
  readonly categories = signal<Category[]>([]);
  readonly formOpen = signal(false);
  readonly editing = signal<Budget | null>(null);
  readonly toDelete = signal<Budget | null>(null);

  readonly cur = this.auth.currency;
  readonly overall = computed(() => this.budgets().find((b) => !b.category) ?? null);
  readonly categoryBudgets = computed(() => this.budgets().filter((b) => !!b.category));
  private i18n = inject(I18nService);
  readonly monthLabel = computed(() => {
    this.i18n.lang();
    return Months.label(this.month());
  });

  readonly form = this.fb.group({
    categoryId: [null as number | null],
    limitAmount: [null as number | null, [Validators.required, Validators.min(1)]],
  });

  constructor() {
    this.api.categories().subscribe((c) => this.categories.set(c));
    effect(() => {
      this.month();
      untracked(() => this.load());
    });
    inject(RealtimeService).on('BUDGETS_CHANGED', 'EXPENSES_CHANGED').pipe(debounceTime(200), takeUntilDestroyed()).subscribe(() => this.load());
  }

  load() {
    this.api.budgets(this.month()).subscribe((b) => this.budgets.set(b));
  }

  open(b: Budget | null) {
    this.editing.set(b);
    this.form.reset({ categoryId: b?.category?.id ?? null, limitAmount: b?.limitAmount ?? null });
    if (b) this.form.controls.categoryId.disable();
    else this.form.controls.categoryId.enable();
    this.formOpen.set(true);
  }

  save() {
    const v = this.form.getRawValue();
    this.api.saveBudget({ categoryId: v.categoryId, period: this.month(), limitAmount: Number(v.limitAmount) }).subscribe({
      next: () => {
        this.toast.success(t('budgets.saved'));
        this.formOpen.set(false);
        this.load();
      },
      error: (err) => this.toast.error(t('common.couldNotSave'), errorMessage(err)),
    });
  }

  copyPrevious() {
    this.api.copyBudgets(this.month()).subscribe((b) => {
      this.budgets.set(b);
      this.toast.info(t(b.length ? 'budgets.copied' : 'budgets.noneLast'));
    });
  }

  remove(b: Budget) {
    this.toDelete.set(null);
    this.api.deleteBudget(b.id).subscribe(() => {
      this.toast.success(t('budgets.deleted'));
      this.load();
    });
  }

  color(p: number) {
    return p >= 100 ? 'var(--danger)' : p >= 80 ? 'var(--warning)' : 'var(--success)';
  }

  abs(n: number) {
    return Math.abs(n);
  }
}

// mobile/src/app/budgets.tsx
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useState } from 'react';
import { View } from 'react-native';
import { errorMessage } from '@/api/client';
import { api } from '@/api/endpoints';
import { Budget } from '@/api/models';
import { qk } from '@/api/queryKeys';
import { useAuth } from '@/auth/AuthContext';
import { Ring } from '@/components/charts';
import { MonthPicker } from '@/components/MonthPicker';
import { useToast } from '@/components/Toast';
import {
  Badge, Button, Card, CategoryDot, confirm, EmptyState, GradientCard, IconButton, Loading, Notice, ProgressBar, Row, Screen, Txt,
} from '@/components/ui';
import { catName, t, useI18n } from '@/i18n';
import { budgetColor, fonts, useTheme } from '@/theme/theme';
import { formatMoney, Months } from '@/utils/format';

export default function BudgetsScreen() {
  const { currency } = useAuth();
  const { colors } = useTheme();
  useI18n();
  const toast = useToast();
  const queryClient = useQueryClient();
  const [month, setMonth] = useState(Months.current());
  const [copying, setCopying] = useState(false);
  const budgets = useQuery({ queryKey: qk.budgets(month), queryFn: () => api.budgets(month) });

  const list = budgets.data ?? [];
  const overall = list.find((b) => !b.category) ?? null;
  const byCategory = list.filter((b) => !!b.category);
  const money = (v: number) => formatMoney(v, currency);

  const open = (b: Budget | null) =>
    router.push({ pathname: '/budget-form', params: b ? { budget: JSON.stringify(b), month } : { month } });

  const copyPrevious = async () => {
    setCopying(true);
    try {
      const copied = await api.copyBudgets(month);
      queryClient.setQueryData(qk.budgets(month), copied);
      queryClient.invalidateQueries({ queryKey: ['dashboard'] });
      toast.info(copied.length ? t('budgets.copied') : t('budgets.noneLast'));
    } catch (err) {
      toast.error(t('budgets.copyError'), errorMessage(err));
    }
    setCopying(false);
  };

  const remove = (b: Budget) =>
    confirm(
      t('budgets.deleteTitle'),
      t('budgets.deleteMsg', { name: b.category ? catName(b.category.name) : t('budgets.overallName') }),
      async () => {
        try {
          await api.deleteBudget(b.id);
          toast.success(t('budgets.deleted'));
          queryClient.invalidateQueries({ queryKey: ['budgets'] });
          queryClient.invalidateQueries({ queryKey: ['dashboard'] });
        } catch (err) {
          toast.error(t('common.couldNotDelete'), errorMessage(err));
        }
      },
    );

  const remaining = (b: Budget, key: 'budgets.remaining' | 'budgets.left') => (
    <Txt variant="small" color={b.remaining < 0 ? colors.danger : colors.textMuted} style={{ flexShrink: 1 }}>
      {t(b.remaining < 0 ? 'budgets.overBy' : key, { amount: money(Math.abs(b.remaining)) })}
    </Txt>
  );

  return (
    <Screen edges={[]} onRefresh={() => budgets.refetch()} refreshing={budgets.isRefetching}>
      <Txt variant="muted">{t('budgets.subtitle')}</Txt>
      <MonthPicker month={month} onChange={setMonth} />
      <Row>
        <Button title={t('budgets.copy')} icon="⧉" variant="ghost" size="sm" onPress={copyPrevious} loading={copying} style={{ flex: 1 }} />
        <Button title={t('budgets.new')} icon="＋" size="sm" onPress={() => open(null)} style={{ flex: 1 }} />
      </Row>

      {budgets.isError ? <Notice tone="danger" text={errorMessage(budgets.error)} /> : null}
      {budgets.isLoading ? <Loading /> : null}

      {overall ? (
        <GradientCard style={{ gap: 12 }}>
          <Row style={{ justifyContent: 'space-between' }}>
            <View style={{ flex: 1 }}>
              <Txt variant="small">{t('budgets.overallTitle')}</Txt>
              <Txt variant="h2" style={{ marginTop: 4 }}>{money(overall.spent)}</Txt>
              <Txt variant="muted">{t('budgets.of', { amount: money(overall.limitAmount) })}</Txt>
            </View>
            <Ring value={overall.percent} size={76} stroke={8} color={budgetColor(colors, overall.percent)}>
              <Txt variant="num">{overall.percent}%</Txt>
            </Ring>
          </Row>
          <ProgressBar percent={overall.percent} color={budgetColor(colors, overall.percent)} height={12} />
          <Row style={{ justifyContent: 'space-between' }}>
            {remaining(overall, 'budgets.remaining')}
            <Row gap={0}>
              <IconButton icon="✏️" label={t('common.edit')} onPress={() => open(overall)} />
              <IconButton icon="🗑️" label={t('common.delete')} tone="danger" onPress={() => remove(overall)} />
            </Row>
          </Row>
        </GradientCard>
      ) : null}

      {byCategory.map((b) => (
        <Card key={b.id} style={{ gap: 10 }} glow={b.percent >= 100 ? colors.danger : undefined}>
          <Row style={{ justifyContent: 'space-between' }}>
            <Row style={{ flex: 1 }} gap={10}>
              <CategoryDot icon={b.category!.icon} color={b.category!.color} size={34} />
              <Txt numberOfLines={1} style={{ fontFamily: fonts.semibold, flexShrink: 1 }}>{catName(b.category!.name)}</Txt>
            </Row>
            <Badge label={`${b.percent}%`} tone={b.percent >= 100 ? 'danger' : b.percent >= 80 ? 'warning' : 'success'} />
          </Row>
          <Txt>
            <Txt style={{ fontFamily: fonts.bold, fontSize: 17 }}>{money(b.spent)}</Txt>
            <Txt variant="muted"> {t('budgets.of', { amount: money(b.limitAmount) })}</Txt>
          </Txt>
          <ProgressBar percent={b.percent} color={budgetColor(colors, b.percent)} />
          <Row style={{ justifyContent: 'space-between' }}>
            {remaining(b, 'budgets.left')}
            <Row gap={0}>
              <IconButton icon="✏️" label={t('common.edit')} onPress={() => open(b)} />
              <IconButton icon="🗑️" label={t('common.delete')} tone="danger" onPress={() => remove(b)} />
            </Row>
          </Row>
        </Card>
      ))}

      {!budgets.isLoading && !list.length ? (
        <Card>
          <EmptyState
            emoji="🎯"
            title={t('budgets.none', { month: Months.label(month) })}
            text={t('budgets.noneHint')}
            action={<Button title={t('budgets.create')} size="sm" onPress={() => open(null)} />}
          />
        </Card>
      ) : null}
    </Screen>
  );
}
