// frontend/src/app/pages/public/login.component.ts
import { Component, inject, input, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { errorMessage } from '../../core/auth.interceptor';
import { AuthService } from '../../core/auth.service';
import { t, TranslatePipe } from '../../core/i18n';
import { AuthLayoutComponent } from './auth-layout.component';

@Component({
  selector: 'app-login',
  imports: [ReactiveFormsModule, RouterLink, AuthLayoutComponent, TranslatePipe],
  template: `
    <app-auth-layout [title]="'auth.welcomeBack' | t" [subtitle]="'auth.signInSubtitle' | t">
      @if (reason() === 'expired') { <div class="alert alert-info">{{ 'auth.expired' | t }}</div> }
      @if (reason() === 'disabled') { <div class="alert alert-warning">{{ 'auth.disabled' | t }}</div> }
      @if (reason() === 'reset') { <div class="alert alert-success">{{ 'auth.resetDone' | t }}</div> }
      @if (error()) { <div class="alert alert-error">{{ error() }}</div> }

      <form [formGroup]="form" (ngSubmit)="submit()">
        <div class="form-field">
          <label for="email">{{ 'common.email' | t }}</label>
          <input id="email" class="input" type="email" formControlName="email" placeholder="you@example.com" autocomplete="email" />
        </div>
        <div class="form-field">
          <div class="row-between">
            <label for="password">{{ 'common.password' | t }}</label>
            <a routerLink="/forgot-password" class="small">{{ 'auth.forgot' | t }}</a>
          </div>
          <div class="input-group">
            <input id="password" class="input" [type]="show() ? 'text' : 'password'" formControlName="password" placeholder="••••••••" autocomplete="current-password" />
            <button type="button" class="icon-btn addon" (click)="show.set(!show())" [attr.aria-label]="show() ? 'Hide password' : 'Show password'">{{ show() ? '🙈' : '👁️' }}</button>
          </div>
        </div>
        <button class="btn btn-primary btn-lg btn-block" type="submit" [disabled]="form.invalid || loading()">
          @if (loading()) { <span class="spinner"></span> } {{ 'auth.signIn' | t }}
        </button>
      </form>

      <p class="muted switch">{{ 'auth.noAccount' | t }} <a routerLink="/register">{{ 'auth.createFree' | t }}</a></p>

      <div class="demo">
        <span class="muted small">{{ 'auth.tryInstantly' | t }}</span>
        <button class="btn btn-ghost btn-sm" (click)="fill('demo@moneymonitor.local', 'Demo@123')">👤 {{ 'auth.demoUser' | t }}</button>
        <button class="btn btn-ghost btn-sm" (click)="fill('admin@moneymonitor.local', 'Admin@123')">🛡️ {{ 'auth.admin' | t }}</button>
      </div>
    </app-auth-layout>
  `,
  styles: [`
    .switch { text-align: center; margin-top: 22px; }
    .demo { display: flex; gap: 8px; align-items: center; justify-content: center; flex-wrap: wrap; margin-top: 28px; padding-top: 20px; border-top: 1px dashed var(--border); }
  `],
})
export class LoginComponent {
  readonly reason = input<string>();
  private auth = inject(AuthService);
  private router = inject(Router);
  private fb = inject(FormBuilder);

  readonly loading = signal(false);
  readonly error = signal('');
  readonly show = signal(false);
  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required],
  });

  fill(email: string, password: string) {
    this.form.setValue({ email, password });
  }

  submit() {
    if (this.form.invalid) return;
    this.loading.set(true);
    this.error.set('');
    const { email, password } = this.form.getRawValue();
    this.auth.login(email, password).subscribe({
      next: () => this.router.navigateByUrl(this.auth.homeRoute()),
      error: (err) => {
        this.error.set(errorMessage(err, t('errors.invalidLogin')));
        this.loading.set(false);
      },
    });
  }
}

// mobile/src/app/(auth)/login.tsx
import { Link, useLocalSearchParams } from 'expo-router';
import { useRef, useState } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { errorMessage } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { AuthShell } from '@/components/AuthShell';
import { Button, Input, Notice, Row, Txt } from '@/components/ui';
import { t, useI18n } from '@/i18n';
import { fonts, useTheme } from '@/theme/theme';

export default function LoginScreen() {
  const { login, logoutReason, clearLogoutReason } = useAuth();
  const { reason: paramReason } = useLocalSearchParams<{ reason?: string }>();
  const { colors } = useTheme();
  useI18n();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [show, setShow] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const passwordRef = useRef<TextInput>(null);

  const reason = logoutReason ?? paramReason;
  const valid = /^\S+@\S+\.\S+$/.test(email.trim()) && password.length > 0;

  const submit = async () => {
    if (!valid || loading) return;
    setLoading(true);
    setError('');
    clearLogoutReason();
    try {
      await login(email.trim(), password);
    } catch (err) {
      setError(errorMessage(err, t('errors.invalidLogin')));
      setLoading(false);
    }
  };

  const fill = (e: string, p: string) => {
    setEmail(e);
    setPassword(p);
  };

  return (
    <AuthShell title={t('auth.welcomeBack')} subtitle={t('auth.signInSubtitle')}>
      <View style={{ gap: 10, marginBottom: 6 }}>
        {reason === 'expired' && <Notice tone="info" text={t('auth.expired')} />}
        {reason === 'disabled' && <Notice tone="warning" text={t('auth.disabled')} />}
        {reason === 'reset' && <Notice tone="success" text={t('auth.resetDone')} />}
        {error ? <Notice tone="danger" text={error} /> : null}
      </View>

      <Input
        label={t('common.email')}
        value={email}
        onChangeText={setEmail}
        placeholder="you@example.com"
        keyboardType="email-address"
        autoCapitalize="none"
        autoComplete="email"
        textContentType="emailAddress"
        returnKeyType="next"
        onSubmitEditing={() => passwordRef.current?.focus()}
      />
      <Input
        ref={passwordRef}
        label={t('common.password')}
        value={password}
        onChangeText={setPassword}
        placeholder="••••••••"
        secureTextEntry={!show}
        autoCapitalize="none"
        autoComplete="current-password"
        textContentType="password"
        returnKeyType="go"
        onSubmitEditing={submit}
        right={
          <Pressable onPress={() => setShow(!show)} hitSlop={8}>
            <Text style={{ fontSize: 17 }}>{show ? '🙈' : '👁️'}</Text>
          </Pressable>
        }
      />
      <Link href="/forgot-password" style={{ alignSelf: 'flex-end', marginTop: -6, marginBottom: 18 }}>
        <Text style={{ color: colors.primaryText, fontFamily: fonts.medium, fontSize: 13 }}>{t('auth.forgot')}</Text>
      </Link>

      <Button title={t('auth.signIn')} size="lg" onPress={submit} loading={loading} disabled={!valid} />

      <Row style={{ justifyContent: 'center', marginTop: 20, flexWrap: 'wrap' }} gap={4}>
        <Txt variant="muted">{t('auth.noAccount')}</Txt>
        <Link href="/register">
          <Text style={{ color: colors.primaryText, fontFamily: fonts.semibold, fontSize: 14 }}>{t('auth.createFree')}</Text>
        </Link>
      </Row>

      <View style={{ marginTop: 26, paddingTop: 18, borderTopWidth: 1, borderStyle: 'dashed', borderColor: colors.border, gap: 10, alignItems: 'center' }}>
        <Txt variant="small">{t('auth.tryInstantly')}</Txt>
        <Row>
          <Button title={t('auth.demoUser')} icon="👤" variant="ghost" size="sm" onPress={() => fill('demo@moneymonitor.local', 'Demo@123')} />
          <Button title={t('auth.admin')} icon="🛡️" variant="ghost" size="sm" onPress={() => fill('admin@moneymonitor.local', 'Admin@123')} />
        </Row>
      </View>
    </AuthShell>
  );
}
