// frontend/src/app/pages/public/register.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { AbstractControl, FormBuilder, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { errorMessage } from '../../core/auth.interceptor';
import { AuthService } from '../../core/auth.service';
import { I18nService, t, tList, TranslatePipe } from '../../core/i18n';
import { CURRENCIES } from '../../core/models';
import { ToastService } from '../../core/ui.service';
import { AuthLayoutComponent } from './auth-layout.component';

export function passwordsMatch(group: AbstractControl): ValidationErrors | null {
  const p = group.get('password')?.value;
  const c = group.get('confirm')?.value;
  return p && c && p !== c ? { mismatch: true } : null;
}

/** 0-4 score used by the strength meter. */
export function passwordScore(p: string): number {
  let score = 0;
  if (p.length >= 8) score++;
  if (/[A-Z]/.test(p) && /[a-z]/.test(p)) score++;
  if (/\d/.test(p)) score++;
  if (/[^A-Za-z0-9]/.test(p) || p.length >= 12) score++;
  return score;
}

@Component({
  selector: 'app-register',
  imports: [ReactiveFormsModule, RouterLink, AuthLayoutComponent, TranslatePipe],
  template: `
    <app-auth-layout [title]="'auth.createTitle' | t" [subtitle]="'auth.createSubtitle' | t">
      @if (error()) { <div class="alert alert-error">{{ error() }}</div> }

      <form [formGroup]="form" (ngSubmit)="submit()">
        <div class="form-field">
          <label for="name">{{ 'common.fullName' | t }}</label>
          <input id="name" class="input" formControlName="fullName" [placeholder]="'auth.yourName' | t" autocomplete="name" [class.invalid]="invalid('fullName')" />
          @if (invalid('fullName')) { <span class="field-error">{{ 'auth.nameRequired' | t }}</span> }
        </div>
        <div class="form-field">
          <label for="email">{{ 'common.email' | t }}</label>
          <input id="email" class="input" type="email" formControlName="email" placeholder="you@example.com" autocomplete="email" [class.invalid]="invalid('email')" />
          @if (invalid('email')) { <span class="field-error">{{ 'auth.validEmail' | t }}</span> }
        </div>
        <div class="form-row">
          <div class="form-field">
            <label for="password">{{ 'common.password' | t }}</label>
            <input id="password" class="input" type="password" formControlName="password" [placeholder]="'auth.minChars' | t" autocomplete="new-password" [class.invalid]="invalid('password')" />
          </div>
          <div class="form-field">
            <label for="confirm">{{ 'common.confirmPassword' | t }}</label>
            <input id="confirm" class="input" type="password" formControlName="confirm" autocomplete="new-password" [class.invalid]="submitted && form.hasError('mismatch')" />
          </div>
        </div>
        @if (password()) {
          <div class="strength">
            @for (i of [1, 2, 3, 4]; track i) { <span [class]="i <= score() ? 'on s' + score() : ''"></span> }
            <small class="muted">{{ strengthLabel() }}</small>
          </div>
        }
        @if (invalid('password')) { <p class="field-error">{{ 'auth.passwordMin' | t }}</p> }
        @if (submitted && form.hasError('mismatch')) { <p class="field-error">{{ 'auth.mismatch' | t }}</p> }

        <div class="form-field">
          <label for="currency">{{ 'common.currency' | t }}</label>
          <select id="currency" class="input" formControlName="currency">
            @for (c of currencies; track c) { <option [value]="c">{{ c }}</option> }
          </select>
        </div>

        <label class="checkbox terms">
          <input type="checkbox" formControlName="terms" />
          <span>{{ 'auth.terms' | t }}</span>
        </label>
        @if (submitted && !form.value.terms) { <p class="field-error">{{ 'auth.acceptTerms' | t }}</p> }

        <button class="btn btn-primary btn-lg btn-block" type="submit" [disabled]="loading()">
          @if (loading()) { <span class="spinner"></span> } {{ 'auth.createBtn' | t }}
        </button>
      </form>
      <p class="muted switch">{{ 'auth.haveAccount' | t }} <a routerLink="/login">{{ 'auth.signIn' | t }}</a></p>
    </app-auth-layout>
  `,
  styles: [`
    .switch { text-align: center; margin-top: 22px; }
    .terms { margin: 4px 0 20px; font-size: 13px; color: var(--text-muted); }
    .strength { display: flex; gap: 6px; align-items: center; margin: -6px 0 14px; }
    .strength span { flex: 1; height: 5px; border-radius: 9px; background: var(--border); }
    .strength .on.s1 { background: var(--danger); } .strength .on.s2 { background: var(--warning); }
    .strength .on.s3 { background: #84cc16; } .strength .on.s4 { background: var(--success); }
    .strength small { width: 70px; text-align: end; }
  `],
})
export class RegisterComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  private toast = inject(ToastService);
  private i18n = inject(I18nService);
  private fb = inject(FormBuilder);

  readonly currencies = CURRENCIES;
  readonly loading = signal(false);
  readonly error = signal('');
  submitted = false;

  readonly form = this.fb.nonNullable.group(
    {
      fullName: ['', [Validators.required, Validators.maxLength(100)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8)]],
      confirm: ['', Validators.required],
      currency: ['MAD'],
      terms: [false],
    },
    { validators: passwordsMatch },
  );

  readonly password = toSignal(this.form.controls.password.valueChanges, { initialValue: '' });
  readonly score = computed(() => passwordScore(this.password()));
  readonly strengthLabel = computed(() => {
    this.i18n.lang();
    return tList('auth.strength')[this.score()];
  });

  invalid(name: string) {
    const c = this.form.get(name);
    return !!c && c.invalid && (c.touched || this.submitted);
  }

  submit() {
    this.submitted = true;
    if (this.form.invalid || !this.form.value.terms) return;
    this.loading.set(true);
    this.error.set('');
    const { fullName, email, password, currency } = this.form.getRawValue();
    this.auth.register({ fullName, email, password, currency }).subscribe({
      next: () => {
        this.toast.success(t('auth.welcomeToast'), t('auth.welcomeToastMsg'));
        this.router.navigateByUrl('/app/dashboard');
      },
      error: (err) => {
        this.error.set(errorMessage(err));
        this.loading.set(false);
      },
    });
  }
}

// mobile/src/app/(auth)/register.tsx
import { Link } from 'expo-router';
import { useState } from 'react';
import { Text, View } from 'react-native';
import { errorMessage } from '@/api/client';
import { CURRENCIES } from '@/api/models';
import { useAuth } from '@/auth/AuthContext';
import { AuthShell } from '@/components/AuthShell';
import { StrengthMeter } from '@/components/StrengthMeter';
import { useToast } from '@/components/Toast';
import { Button, Chip, Input, Notice, Row, Toggle, Txt } from '@/components/ui';
import { t, useI18n } from '@/i18n';
import { fonts, useTheme } from '@/theme/theme';

export default function RegisterScreen() {
  const { register } = useAuth();
  const toast = useToast();
  const { colors } = useTheme();
  const { lang } = useI18n();
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [currency, setCurrency] = useState('MAD');
  const [terms, setTerms] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const errors = {
    fullName: !fullName.trim() ? t('auth.nameRequired') : '',
    email: !/^\S+@\S+\.\S+$/.test(email.trim()) ? t('auth.validEmail') : '',
    password: password.length < 8 ? t('auth.passwordMin') : '',
    confirm: !confirm ? t('auth.confirmRequired') : password !== confirm ? t('auth.mismatch') : '',
    terms: !terms ? t('auth.acceptTerms') : '',
  };
  const show = (key: keyof typeof errors) => (submitted ? errors[key] : '');

  const submit = async () => {
    setSubmitted(true);
    if (Object.values(errors).some(Boolean) || loading) return;
    setLoading(true);
    setError('');
    try {
      // The language picked on the sign-in screens becomes the account language.
      await register({ fullName: fullName.trim(), email: email.trim(), password, currency, language: lang });
      toast.success(t('auth.welcomeToast'), t('auth.welcomeToastMsg'));
    } catch (err) {
      setError(errorMessage(err));
      setLoading(false);
    }
  };

  return (
    <AuthShell title={t('auth.createTitle')} subtitle={t('auth.createSubtitle')}>
      {error ? <View style={{ marginBottom: 12 }}><Notice tone="danger" text={error} /></View> : null}
      <Input label={t('common.fullName')} value={fullName} onChangeText={setFullName} placeholder={t('auth.yourName')} autoComplete="name" maxLength={100} error={show('fullName')} />
      <Input
        label={t('common.email')}
        value={email}
        onChangeText={setEmail}
        placeholder="you@example.com"
        keyboardType="email-address"
        autoCapitalize="none"
        autoComplete="email"
        error={show('email')}
      />
      <Input
        label={t('common.password')}
        value={password}
        onChangeText={setPassword}
        placeholder={t('auth.minChars')}
        secureTextEntry
        autoCapitalize="none"
        textContentType="newPassword"
        error={show('password')}
      />
      <StrengthMeter password={password} />
      <Input
        label={t('common.confirmPassword')}
        value={confirm}
        onChangeText={setConfirm}
        secureTextEntry
        autoCapitalize="none"
        textContentType="newPassword"
        error={show('confirm')}
      />

      <Txt variant="label" style={{ marginBottom: 8 }}>{t('common.currency')}</Txt>
      <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 16 }}>
        {CURRENCIES.map((c) => (
          <Chip key={c} label={c} selected={currency === c} onPress={() => setCurrency(c)} />
        ))}
      </View>

      <Toggle label={t('auth.terms')} value={terms} onChange={setTerms} />
      {show('terms') ? <Txt variant="small" color={colors.danger} style={{ marginTop: -8, marginBottom: 12 }}>{errors.terms}</Txt> : null}

      <Button title={t('auth.createBtn')} size="lg" onPress={submit} loading={loading} />

      <Row style={{ justifyContent: 'center', marginTop: 20, flexWrap: 'wrap' }} gap={4}>
        <Txt variant="muted">{t('auth.haveAccount')}</Txt>
        <Link href="/login">
          <Text style={{ color: colors.primaryText, fontFamily: fonts.semibold, fontSize: 14 }}>{t('auth.signIn')}</Text>
        </Link>
      </Row>
    </AuthShell>
  );
}
