// frontend/src/app/pages/public/verify-email.component.ts
import { Component, inject, input, OnDestroy, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { errorMessage } from '../../core/auth.interceptor';
import { AuthService } from '../../core/auth.service';
import { t, TranslatePipe } from '../../core/i18n';
import { ToastService } from '../../core/ui.service';
import { AuthLayoutComponent } from './auth-layout.component';

const RESEND_SECONDS = 60;

/** Enter the 6-digit code emailed at sign-up (or after signing in with an unconfirmed email). */
@Component({
  selector: 'app-verify-email',
  imports: [FormsModule, RouterLink, AuthLayoutComponent, TranslatePipe],
  template: `
    <app-auth-layout [title]="'auth.verifyTitle' | t" [subtitle]="'auth.verifySubtitle' | t: { email: email() ?? '' }">
      @if (info()) { <div class="alert alert-info">{{ info() }}</div> }
      @if (error()) { <div class="alert alert-error">{{ error() }}</div> }

      <form (ngSubmit)="submit()">
        <div class="form-field">
          <label for="code">{{ 'auth.codeLabel' | t }}</label>
          <input
            id="code"
            class="input code"
            [class.invalid]="!!error()"
            name="code"
            [ngModel]="code()"
            (ngModelChange)="onChange($event)"
            inputmode="numeric"
            autocomplete="one-time-code"
            maxlength="6"
            placeholder="••••••"
            autofocus
          />
        </div>
        <button class="btn btn-primary btn-lg btn-block" type="submit" [disabled]="code().length !== 6 || loading()">
          @if (loading()) { <span class="spinner"></span> } {{ 'auth.verifyBtn' | t }}
        </button>
      </form>

      <div class="links">
        <button type="button" class="link-btn" (click)="resend()" [disabled]="wait() > 0">
          {{ wait() > 0 ? ('auth.resendIn' | t: { s: wait() }) : ('auth.resend' | t) }}
        </button>
        <p class="muted small">{{ 'auth.spamHint' | t }}</p>
        <a routerLink="/register" class="small">{{ 'auth.wrongEmail' | t }}</a>
      </div>
    </app-auth-layout>
  `,
  styles: [`
    .code { height: 64px; font-family: var(--font-display); font-size: 30px; letter-spacing: 12px; text-align: center; }
    .links { display: grid; gap: 12px; justify-items: center; text-align: center; margin-top: 22px; }
    .link-btn { background: none; border: 0; padding: 0; font: inherit; font-weight: 600; color: var(--primary-text); cursor: pointer; }
    .link-btn:disabled { color: var(--text-muted); cursor: default; }
  `],
})
export class VerifyEmailComponent implements OnInit, OnDestroy {
  readonly email = input<string>();
  readonly notice = input<string>();
  private auth = inject(AuthService);
  private router = inject(Router);
  private toast = inject(ToastService);

  readonly code = signal('');
  readonly loading = signal(false);
  readonly error = signal('');
  readonly info = signal('');
  readonly wait = signal(RESEND_SECONDS);
  private timer?: ReturnType<typeof setInterval>;

  ngOnInit() {
    if (!this.email()) {
      this.router.navigateByUrl('/register');
      return;
    }
    if (this.notice() === 'notVerified') this.info.set(t('auth.notVerified'));
    this.startCountdown();
  }

  ngOnDestroy() {
    clearInterval(this.timer);
  }

  onChange(value: string) {
    const digits = (value ?? '').replace(/\D/g, '').slice(0, 6);
    this.code.set(digits);
    if (digits.length === 6) this.submit();
  }

  submit() {
    if (this.code().length !== 6 || this.loading()) return;
    this.loading.set(true);
    this.error.set('');
    this.auth.verifyEmail(this.email()!, this.code()).subscribe({
      next: () => {
        this.toast.success(t('auth.verified'), t('auth.welcomeToastMsg'));
        this.router.navigateByUrl(this.auth.homeRoute());
      },
      error: (err) => {
        this.error.set(errorMessage(err));
        this.code.set('');
        this.loading.set(false);
      },
    });
  }

  resend() {
    this.error.set('');
    this.auth.resendVerification(this.email()!).subscribe({
      next: () => {
        this.info.set(t('auth.resent'));
        this.startCountdown();
      },
      error: (err) => this.error.set(errorMessage(err)),
    });
  }

  private startCountdown() {
    clearInterval(this.timer);
    this.wait.set(RESEND_SECONDS);
    this.timer = setInterval(() => {
      this.wait.update((w) => w - 1);
      if (this.wait() <= 0) clearInterval(this.timer);
    }, 1000);
  }
}

// mobile/src/app/(auth)/verify-email.tsx
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { errorMessage } from '@/api/client';
import { api } from '@/api/endpoints';
import { useAuth } from '@/auth/AuthContext';
import { AuthShell } from '@/components/AuthShell';
import { useToast } from '@/components/Toast';
import { Button, Notice, Txt } from '@/components/ui';
import { t, useI18n } from '@/i18n';
import { fonts, radius, useTheme } from '@/theme/theme';
import { haptics } from '@/utils/haptics';

const RESEND_SECONDS = 60;

/** Enter the 6-digit code emailed at sign-up (or after signing in with an unconfirmed email). */
export default function VerifyEmailScreen() {
  const { email = '', notice } = useLocalSearchParams<{ email?: string; notice?: string }>();
  const { verifyEmail } = useAuth();
  const { colors } = useTheme();
  const toast = useToast();
  useI18n();
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [info, setInfo] = useState(notice === 'notVerified' ? t('auth.notVerified') : '');
  const [wait, setWait] = useState(RESEND_SECONDS);

  useEffect(() => {
    if (wait <= 0) return;
    const timer = setTimeout(() => setWait((w) => w - 1), 1000);
    return () => clearTimeout(timer);
  }, [wait]);

  const submit = async (value = code) => {
    if (value.length !== 6 || loading) return;
    setLoading(true);
    setError('');
    try {
      await verifyEmail(email, value);
      haptics.success();
      toast.success(t('auth.verified'), t('auth.welcomeToastMsg'));
      // Signed in: the root layout switches to the app.
    } catch (err) {
      setError(errorMessage(err));
      setCode('');
      setLoading(false);
    }
  };

  const onChange = (text: string) => {
    const digits = text.replace(/\D/g, '').slice(0, 6);
    setCode(digits);
    if (digits.length === 6) submit(digits);
  };

  const resend = async () => {
    setError('');
    try {
      await api.resendVerification(email);
      setInfo(t('auth.resent'));
      setWait(RESEND_SECONDS);
    } catch (err) {
      setError(errorMessage(err));
    }
  };

  return (
    <AuthShell title={t('auth.verifyTitle')} subtitle={t('auth.verifySubtitle', { email })}>
      <View style={{ gap: 10, marginBottom: 6 }}>
        {info ? <Notice tone="info" text={info} /> : null}
        {error ? <Notice tone="danger" text={error} /> : null}
      </View>

      <Txt variant="label" style={{ marginBottom: 8 }}>{t('auth.codeLabel')}</Txt>
      <TextInput
        value={code}
        onChangeText={onChange}
        keyboardType="number-pad"
        textContentType="oneTimeCode"
        autoComplete="one-time-code"
        maxLength={6}
        autoFocus
        placeholder="••••••"
        placeholderTextColor={colors.textDim}
        selectionColor={colors.primary}
        style={{
          height: 64,
          borderRadius: radius.md,
          borderWidth: 1,
          borderColor: error ? colors.danger : colors.borderStrong,
          backgroundColor: colors.surface2,
          color: colors.text,
          fontFamily: fonts.display,
          fontSize: 30,
          letterSpacing: 12,
          textAlign: 'center',
          marginBottom: 16,
        }}
      />

      <Button title={t('auth.verifyBtn')} size="lg" onPress={() => submit()} loading={loading} disabled={code.length !== 6} />

      <View style={{ alignItems: 'center', gap: 14, marginTop: 22 }}>
        <Pressable onPress={resend} disabled={wait > 0} hitSlop={8}>
          <Text style={{ color: wait > 0 ? colors.textDim : colors.primaryText, fontFamily: fonts.semibold, fontSize: 14 }}>
            {wait > 0 ? t('auth.resendIn', { s: wait }) : t('auth.resend')}
          </Text>
        </Pressable>
        <Txt variant="small" style={{ textAlign: 'center' }}>{t('auth.spamHint')}</Txt>
        <Pressable onPress={() => router.replace('/register')} hitSlop={8}>
          <Text style={{ color: colors.textMuted, fontFamily: fonts.medium, fontSize: 13 }}>{t('auth.wrongEmail')}</Text>
        </Pressable>
      </View>
    </AuthShell>
  );
}
