// frontend/src/app/pages/user/advisor.component.ts
import { Component, effect, ElementRef, inject, signal, untracked, viewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../core/api.service';
import { errorMessage } from '../../core/auth.interceptor';
import { AuthService } from '../../core/auth.service';
import { I18nService, t, tList, TranslatePipe } from '../../core/i18n';
import { Advice, AiStatus, ChatMessage } from '../../core/models';
import { Months } from '../../core/ui.service';
import { MonthPickerComponent } from '../../shared/month-picker.component';
import { MarkdownPipe, MoneyPipe, TimeAgoPipe } from '../../shared/pipes';

type Tab = 'month' | 'year' | 'savings';

@Component({
  selector: 'app-advisor',
  imports: [FormsModule, RouterLink, MonthPickerComponent, MarkdownPipe, MoneyPipe, TimeAgoPipe, TranslatePipe],
  template: `
    <div class="page">
      <div class="page-header">
        <div>
          <h1>{{ 'advisor.title' | t }}</h1>
          <p>{{ 'web.advisor.subtitle' | t }}</p>
        </div>
        @if (status(); as s) {
          <span class="badge" [class.badge-success]="s.configured" [class.badge-warning]="!s.configured">
            {{ s.configured ? '🟢 ' + s.provider + ' · ' + s.model : ('web.advisor.offlineLong' | t) }}
          </span>
        }
      </div>

      <div class="layout">
        <!-- Advice -->
        <div class="card advice">
          <div class="card-header wrap">
            <div class="tabs">
              <button [class.active]="tab() === 'month'" (click)="tab.set('month')">{{ 'web.advisor.monthlyReview' | t }}</button>
              <button [class.active]="tab() === 'year'" (click)="tab.set('year')">{{ 'web.advisor.yearReview' | t }}</button>
              <button [class.active]="tab() === 'savings'" (click)="tab.set('savings')">{{ 'web.advisor.savingsPlan' | t }}</button>
            </div>
            <div class="row">
              @if (tab() === 'month') {
                <app-month-picker [(month)]="month" />
              } @else if (tab() === 'year') {
                <select class="input year" [ngModel]="year()" (ngModelChange)="year.set(+$event)">
                  @for (y of years; track y) { <option [value]="y">{{ y }}</option> }
                </select>
              }
              <button class="btn btn-ghost btn-sm" (click)="load(true)" [disabled]="loading()">↻ {{ 'common.regenerate' | t }}</button>
            </div>
          </div>

          @if (tab() === 'savings') {
            <div class="savings-intro">
              <p class="muted">{{ 'advisor.savingsIntro' | t }}</p>
              <div class="row-between">
                <b>{{ 'dashboard.savingsGoal' | t }}:
                  {{ auth.user()?.savingsGoal ? ('common.perMonth' | t: { amount: (auth.user()?.savingsGoal | money: auth.currency()) }) : '—' }}</b>
                <a routerLink="/app/profile" class="small">{{ 'advisor.changeGoal' | t }}</a>
              </div>
            </div>
          }

          @if (loading()) {
            <div class="thinking">
              <div class="orb"></div>
              <p><b>{{ 'advisor.analysing' | t }}</b></p>
              <p class="muted small">{{ 'advisor.analysingHint' | t }}</p>
            </div>
          } @else if (advice()) {
            <div class="markdown" [innerHTML]="advice()!.content | markdown"></div>
            <div class="meta muted small">
              {{ 'advisor.generated' | t: { when: (advice()!.createdAt | timeAgo), source: advice()!.source === 'rules' ? ('advisor.builtIn' | t) : advice()!.source } }}
            </div>
          } @else if (error()) {
            <div class="alert alert-error">{{ error() }}</div>
          }
        </div>

        <!-- Chat -->
        <div class="card chat">
          <div class="card-header">
            <h3>💬 {{ 'advisor.askPenny' | t }}</h3>
            @if (messages().length) { <button class="btn btn-ghost btn-sm" (click)="messages.set([])">{{ 'advisor.clear' | t }}</button> }
          </div>
          <div class="messages" #scroller>
            @if (!messages().length) {
              <div class="welcome">
                <div class="emoji">🤖</div>
                <p>{{ 'advisor.chatHello' | t }}</p>
                <div class="suggestions">
                  @for (s of suggestions(); track s) { <button class="chip" (click)="send(s)">{{ s }}</button> }
                </div>
              </div>
            }
            @for (m of messages(); track $index) {
              <div class="msg" [class.me]="m.role === 'user'">
                @if (m.role === 'assistant') { <span class="bot">✨</span> }
                <div class="bubble">
                  @if (m.role === 'assistant') { <div class="markdown" [innerHTML]="m.content | markdown"></div> } @else { {{ m.content }} }
                </div>
              </div>
            }
            @if (sending()) {
              <div class="msg"><span class="bot">✨</span><div class="bubble typing"><span></span><span></span><span></span></div></div>
            }
          </div>
          <form class="composer" (ngSubmit)="send(draft)">
            <input class="input" name="draft" [(ngModel)]="draft" [placeholder]="'advisor.placeholder' | t" maxlength="2000" autocomplete="off" />
            <button class="btn btn-primary" [disabled]="!draft.trim() || sending()">{{ 'advisor.send' | t }}</button>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .layout { display: grid; grid-template-columns: 1.15fr 1fr; gap: 20px; align-items: start; }
    @media (max-width: 1100px) { .layout { grid-template-columns: 1fr; } }
    .wrap { flex-wrap: wrap; }
    .year { width: 110px; height: 36px; }
    .advice .markdown { font-size: 14.5px; }
    .savings-intro { display: grid; gap: 8px; padding: 12px 14px; margin-bottom: 16px; border-radius: 14px; background: var(--primary-soft); }
    .meta { margin-top: 18px; padding-top: 14px; border-top: 1px solid var(--border); }
    .thinking { text-align: center; padding: 50px 10px; display: grid; gap: 6px; justify-items: center; }
    .orb { width: 58px; height: 58px; border-radius: 50%; background: var(--gradient); margin-bottom: 12px; animation: breathe 1.4s ease-in-out infinite; box-shadow: 0 0 40px rgba(124,58,237,.45); }
    @keyframes breathe { 50% { transform: scale(.82); opacity: .7; } }

    .chat { display: flex; flex-direction: column; height: calc(100vh - 190px); min-height: 520px; position: sticky; top: 84px; padding-bottom: 16px; }
    .messages { flex: 1; overflow-y: auto; display: flex; flex-direction: column; gap: 14px; padding: 4px 2px 12px; }
    .welcome { text-align: center; margin: auto 0; color: var(--text-muted); }
    .welcome .emoji { font-size: 42px; margin-bottom: 8px; }
    .suggestions { display: flex; flex-wrap: wrap; gap: 8px; justify-content: center; margin-top: 14px; }
    .chip { border: 1px solid var(--border); background: var(--surface-2); color: var(--text); border-radius: 999px; padding: 8px 14px; font: inherit; font-size: 13px; cursor: pointer; }
    .chip:hover { border-color: var(--primary); color: var(--primary-text); }
    .msg { display: flex; gap: 10px; align-items: flex-end; }
    .msg.me { justify-content: flex-end; }
    .bot { width: 30px; height: 30px; border-radius: 10px; background: var(--gradient); display: grid; place-items: center; flex-shrink: 0; font-size: 14px; }
    .bubble { max-width: 85%; padding: 11px 15px; border-radius: 16px; background: var(--surface-2); border: 1px solid var(--border); font-size: 14px; border-end-start-radius: 4px; }
    .bubble .markdown p:last-child, .bubble .markdown ul:last-child { margin-bottom: 0; }
    .me .bubble { background: var(--gradient); color: #fff; border: none; border-end-start-radius: 16px; border-end-end-radius: 4px; }
    .typing { display: flex; gap: 4px; padding: 14px 16px; }
    .typing span { width: 7px; height: 7px; border-radius: 50%; background: var(--text-muted); animation: blink 1.2s infinite; }
    .typing span:nth-child(2) { animation-delay: .2s; } .typing span:nth-child(3) { animation-delay: .4s; }
    @keyframes blink { 0%, 80%, 100% { opacity: .25; } 40% { opacity: 1; } }
    .composer { display: flex; gap: 10px; padding-top: 12px; border-top: 1px solid var(--border); }
    .chat { border-color: color-mix(in srgb, var(--violet) 30%, var(--border)); }
    @media (max-width: 1100px) { .chat { position: relative; top: 0; height: 70vh; min-height: 460px; } }
    @media (max-width: 760px) { .wrap .row { width: 100%; justify-content: space-between; } .bubble { max-width: 92%; } }
  `],
})
export class AdvisorComponent {
  private api = inject(ApiService);
  private i18n = inject(I18nService);
  readonly auth = inject(AuthService);
  private scroller = viewChild<ElementRef<HTMLElement>>('scroller');

  readonly tab = signal<Tab>('month');
  readonly month = signal(Months.current());
  readonly year = signal(new Date().getFullYear());
  readonly years = Array.from({ length: 5 }, (_, i) => new Date().getFullYear() - i);
  readonly advice = signal<Advice | null>(null);
  readonly status = signal<AiStatus | null>(null);
  readonly loading = signal(false);
  readonly error = signal('');
  readonly messages = signal<ChatMessage[]>([]);
  readonly sending = signal(false);
  draft = '';

  suggestions() {
    this.i18n.lang();
    return tList('advisor.suggestions');
  }

  constructor() {
    this.api.aiStatus().subscribe((s) => this.status.set(s));
    // Reload when the tab, period or language changes (AI texts are generated per language).
    effect(() => {
      this.tab();
      this.month();
      this.year();
      this.i18n.lang();
      untracked(() => this.load(false));
    });
  }

  load(refresh: boolean) {
    this.loading.set(true);
    this.error.set('');
    const tab = this.tab();
    const req =
      tab === 'month' ? this.api.monthlyAdvice(this.month(), refresh)
        : tab === 'year' ? this.api.yearlyAdvice(this.year(), refresh)
          : this.api.savingsAdvice(refresh);
    req.subscribe({
      next: (a) => {
        this.advice.set(a);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set(errorMessage(err));
        this.loading.set(false);
      },
    });
  }

  send(text: string) {
    const message = text.trim();
    if (!message || this.sending()) return;
    const history = this.messages();
    this.messages.set([...history, { role: 'user', content: message }]);
    this.draft = '';
    this.sending.set(true);
    this.scrollDown();
    this.api.chat(message, history).subscribe({
      next: (r) => {
        this.messages.update((m) => [...m, { role: 'assistant', content: r.reply }]);
        this.sending.set(false);
        this.scrollDown();
      },
      error: (err) => {
        this.messages.update((m) => [...m, { role: 'assistant', content: '⚠️ ' + (errorMessage(err) || t('common.somethingWrong')) }]);
        this.sending.set(false);
      },
    });
  }

  private scrollDown() {
    setTimeout(() => {
      const el = this.scroller()?.nativeElement;
      if (el) el.scrollTo({ top: el.scrollHeight, behavior: 'smooth' });
    });
  }
}

// mobile/src/app/(tabs)/advisor.tsx
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { errorMessage } from '@/api/client';
import { api } from '@/api/endpoints';
import { ChatMessage } from '@/api/models';
import { qk } from '@/api/queryKeys';
import { useAuth } from '@/auth/AuthContext';
import { AdviceBody } from '@/components/AdviceBody';
import { Markdown } from '@/components/Markdown';
import { MonthPicker } from '@/components/MonthPicker';
import { Badge, Button, Card, Chip, Row, Txt } from '@/components/ui';
import { t, tList, useI18n } from '@/i18n';
import { fonts, radius, useTheme } from '@/theme/theme';
import { formatMoney, Months } from '@/utils/format';

type Tab = 'month' | 'year' | 'savings' | 'chat';

export default function AdvisorScreen() {
  const { colors } = useTheme();
  useI18n();
  const [tab, setTab] = useState<Tab>('month');
  const status = useQuery({ queryKey: qk.aiStatus, queryFn: api.aiStatus, staleTime: 5 * 60_000 });
  const s = status.data;

  return (
    <SafeAreaView edges={['top']} style={{ flex: 1, backgroundColor: colors.bg }}>
      <View style={{ paddingHorizontal: 16, paddingTop: 16, gap: 10 }}>
        <Row style={{ justifyContent: 'space-between' }}>
          <Txt variant="h1">{t('advisor.title')}</Txt>
          {s ? (
            <Badge
              label={s.configured ? `🟢 ${s.provider}${s.model ? ' · ' + s.model : ''}` : t('advisor.offline')}
              tone={s.configured ? 'success' : 'warning'}
            />
          ) : null}
        </Row>
        <Segmented
          value={tab}
          onChange={setTab}
          options={[
            { value: 'month', label: t('advisor.monthly') },
            { value: 'year', label: t('advisor.year') },
            { value: 'savings', label: t('advisor.savings') },
            { value: 'chat', label: t('advisor.penny') },
          ]}
        />
      </View>
      {tab === 'chat' ? <Chat /> : tab === 'savings' ? <SavingsView /> : <AdviceView kind={tab} />}
    </SafeAreaView>
  );
}

function Segmented<T extends string>({ value, onChange, options }: { value: T; onChange: (v: T) => void; options: { value: T; label: string }[] }) {
  const { colors } = useTheme();
  return (
    <View style={{ flexDirection: 'row', backgroundColor: colors.surface2, borderRadius: radius.md, padding: 4, borderWidth: 1, borderColor: colors.border }}>
      {options.map((o) => {
        const active = o.value === value;
        return (
          <Pressable
            key={o.value}
            onPress={() => onChange(o.value)}
            style={{ flex: 1, paddingVertical: 9, borderRadius: radius.sm, alignItems: 'center', backgroundColor: active ? colors.primarySoft : 'transparent' }}
          >
            <Text
              numberOfLines={1}
              adjustsFontSizeToFit
              style={{ color: active ? colors.primaryText : colors.textMuted, fontFamily: active ? fonts.semibold : fonts.medium, fontSize: 13 }}
            >
              {o.label}
            </Text>
          </Pressable>
        );
      })}
    </View>
  );
}

function AdviceView({ kind }: { kind: 'month' | 'year' }) {
  const { colors } = useTheme();
  const queryClient = useQueryClient();
  const [month, setMonth] = useState(Months.current());
  const [year, setYear] = useState(new Date().getFullYear());
  const [regenerating, setRegenerating] = useState(false);
  const [regenError, setRegenError] = useState('');
  const years = Array.from({ length: 5 }, (_, i) => new Date().getFullYear() - i);

  const key = kind === 'month' ? qk.monthlyAdvice(month) : qk.yearlyAdvice(year);
  const fetcher = (refresh: boolean) => (kind === 'month' ? api.monthlyAdvice(month, refresh) : api.yearlyAdvice(year, refresh));
  const advice = useQuery({ queryKey: key, queryFn: () => fetcher(false), staleTime: 5 * 60_000 });

  const regenerate = async () => {
    setRegenerating(true);
    setRegenError('');
    try {
      queryClient.setQueryData(key, await fetcher(true));
    } catch (err) {
      setRegenError(errorMessage(err));
    }
    setRegenerating(false);
  };

  return (
    <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 120, gap: 14 }}>
      <Row>
        <View style={{ flex: 1 }}>
          {kind === 'month' ? (
            <MonthPicker month={month} onChange={setMonth} />
          ) : (
            <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 7 }}>
              {years.map((y) => (
                <Chip key={y} label={String(y)} selected={y === year} onPress={() => setYear(y)} />
              ))}
            </ScrollView>
          )}
        </View>
        <Button title={t('common.regenerate')} icon="↻" variant="ghost" size="sm" onPress={regenerate} disabled={advice.isLoading || regenerating} height={42} />
      </Row>

      <Card glow={colors.violet}>
        <AdviceBody
          advice={advice.data}
          loading={advice.isLoading || regenerating}
          error={regenError || (advice.isError ? errorMessage(advice.error) : undefined)}
        />
      </Card>
    </ScrollView>
  );
}

/** Plan to reach the monthly savings goal from the profile. */
function SavingsView() {
  const { colors } = useTheme();
  const { user, currency } = useAuth();
  const queryClient = useQueryClient();
  const [regenerating, setRegenerating] = useState(false);
  const [regenError, setRegenError] = useState('');
  const advice = useQuery({ queryKey: qk.savingsAdvice, queryFn: () => api.savingsAdvice(), staleTime: 5 * 60_000 });

  const regenerate = async () => {
    setRegenerating(true);
    setRegenError('');
    try {
      queryClient.setQueryData(qk.savingsAdvice, await api.savingsAdvice(true));
    } catch (err) {
      setRegenError(errorMessage(err));
    }
    setRegenerating(false);
  };

  return (
    <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 120, gap: 14 }}>
      <Card style={{ backgroundColor: colors.primarySoft, borderColor: colors.primarySoft, gap: 8 }}>
        <Txt variant="muted">{t('advisor.savingsIntro')}</Txt>
        <Row style={{ justifyContent: 'space-between', flexWrap: 'wrap' }}>
          <Txt style={{ fontFamily: fonts.semibold }}>
            {t('dashboard.savingsGoal')}: {user?.savingsGoal ? t('common.perMonth', { amount: formatMoney(user.savingsGoal, currency) }) : '—'}
          </Txt>
          <Pressable onPress={() => router.push('/profile')} hitSlop={8}>
            <Text style={{ color: colors.primaryText, fontFamily: fonts.semibold, fontSize: 13 }}>{t('advisor.changeGoal')}</Text>
          </Pressable>
        </Row>
      </Card>
      <Row style={{ justifyContent: 'flex-end' }}>
        <Button title={t('common.regenerate')} icon="↻" variant="ghost" size="sm" onPress={regenerate} disabled={advice.isLoading || regenerating} />
      </Row>
      <Card glow={colors.violet}>
        <AdviceBody
          advice={advice.data}
          loading={advice.isLoading || regenerating}
          error={regenError || (advice.isError ? errorMessage(advice.error) : undefined)}
        />
      </Card>
    </ScrollView>
  );
}

function Chat() {
  const { colors } = useTheme();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [draft, setDraft] = useState('');
  const [sending, setSending] = useState(false);
  const scroller = useRef<ScrollView>(null);

  const send = async (text: string) => {
    const message = text.trim();
    if (!message || sending) return;
    const history = messages;
    setMessages([...history, { role: 'user', content: message }]);
    setDraft('');
    setSending(true);
    try {
      const r = await api.chat(message, history);
      setMessages((m) => [...m, { role: 'assistant', content: r.reply }]);
    } catch (err) {
      setMessages((m) => [...m, { role: 'assistant', content: '⚠️ ' + errorMessage(err) }]);
    }
    setSending(false);
  };

  return (
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView
        ref={scroller}
        contentContainerStyle={{ padding: 16, gap: 12, flexGrow: 1 }}
        onContentSizeChange={() => scroller.current?.scrollToEnd({ animated: true })}
        keyboardShouldPersistTaps="handled"
      >
        {!messages.length ? (
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', gap: 8 }}>
            <Text style={{ fontSize: 42 }}>🤖</Text>
            <Txt variant="h3" style={{ textAlign: 'center' }}>{t('advisor.askPenny')}</Txt>
            <Txt variant="muted" style={{ textAlign: 'center' }}>{t('advisor.chatHello')}</Txt>
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'center', marginTop: 8 }}>
              {tList('advisor.suggestions').map((s) => (
                <Chip key={s} label={s} onPress={() => send(s)} />
              ))}
            </View>
          </View>
        ) : (
          messages.map((m, i) => (
            <View key={i} style={{ flexDirection: 'row', gap: 8, alignItems: 'flex-end', justifyContent: m.role === 'user' ? 'flex-end' : 'flex-start' }}>
              {m.role === 'assistant' ? <Bot /> : null}
              {m.role === 'user' ? (
                <LinearGradient colors={colors.gradient} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={[bubble, { borderBottomRightRadius: 4 }]}>
                  <Text style={{ color: '#fff', fontFamily: fonts.body, fontSize: 14.5 }}>{m.content}</Text>
                </LinearGradient>
              ) : (
                <View style={[bubble, { backgroundColor: colors.surfaceSolid, borderWidth: 1, borderColor: colors.border, borderBottomLeftRadius: 4 }]}>
                  <Markdown size={14}>{m.content}</Markdown>
                </View>
              )}
            </View>
          ))
        )}
        {sending ? (
          <View style={{ flexDirection: 'row', gap: 8, alignItems: 'flex-end' }}>
            <Bot />
            <View style={[bubble, { backgroundColor: colors.surfaceSolid, borderWidth: 1, borderColor: colors.border }]}>
              <Txt variant="muted">{t('advisor.typing')}</Txt>
            </View>
          </View>
        ) : null}
      </ScrollView>

      <View style={{ flexDirection: 'row', gap: 8, padding: 12, borderTopWidth: 1, borderColor: colors.border, backgroundColor: colors.bg }}>
        <TextInput
          value={draft}
          onChangeText={setDraft}
          placeholder={t('advisor.placeholder')}
          placeholderTextColor={colors.textDim}
          maxLength={2000}
          multiline
          style={{
            flex: 1,
            maxHeight: 110,
            minHeight: 44,
            color: colors.text,
            fontFamily: fonts.body,
            fontSize: 15,
            backgroundColor: colors.surface2,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: radius.md,
            paddingHorizontal: 14,
            paddingTop: 12,
            paddingBottom: 12,
          }}
        />
        {messages.length ? (
          <Button title={t('advisor.clear')} variant="ghost" size="sm" onPress={() => setMessages([])} height={44} style={{ alignSelf: 'flex-end' }} />
        ) : null}
        <Button title={t('advisor.send')} size="sm" onPress={() => send(draft)} disabled={!draft.trim() || sending} height={44} style={{ alignSelf: 'flex-end' }} />
      </View>
    </KeyboardAvoidingView>
  );
}

function Bot() {
  const { colors } = useTheme();
  return (
    <LinearGradient colors={colors.gradient} style={{ width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ fontSize: 14 }}>✨</Text>
    </LinearGradient>
  );
}

const bubble = { maxWidth: '85%' as const, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 16 };
