// frontend/src/app/pages/user/expenses.component.ts
import { Component, computed, effect, inject, signal, untracked } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { debounceTime, Subject } from 'rxjs';
import { ApiService, downloadBlob } from '../../core/api.service';
import { errorMessage } from '../../core/auth.interceptor';
import { AuthService } from '../../core/auth.service';
import { Category, Expense, PAYMENT_METHODS } from '../../core/models';
import { RealtimeService } from '../../core/realtime.service';
import { Months, ToastService } from '../../core/ui.service';
import { ExpenseFormComponent } from '../../shared/expense-form.component';
import { ConfirmComponent } from '../../shared/modal.component';
import { MonthPickerComponent } from '../../shared/month-picker.component';
import { LocalDatePipe, MoneyPipe } from '../../shared/pipes';
import { catName, CategoryNamePipe, I18nService, t, tList, TranslatePipe } from '../../core/i18n';

@Component({
  selector: 'app-expenses',
  imports: [FormsModule, MonthPickerComponent, MoneyPipe, ExpenseFormComponent, ConfirmComponent, TranslatePipe, CategoryNamePipe, LocalDatePipe],
  template: `
    <div class="page">
      <div class="page-header">
        <div>
          <h1>{{ 'expenses.title' | t }}</h1>
          <p>{{ 'expenses.subtitle' | t }}</p>
        </div>
        <div class="header-actions">
          <app-month-picker [(month)]="month" />
          <button class="btn btn-ghost" (click)="exportCsv()" [disabled]="!expenses().length">⬇ CSV</button>
          <button class="btn btn-primary hide-mobile" (click)="openForm(null)">＋ {{ 'expenses.newTitle' | t }}</button>
        </div>
      </div>

      <div class="card">
        <div class="total-strip">
          <div><span class="eyebrow">{{ 'expenses.spentIn' | t: { month: monthLabel() } }}</span><div class="total num gradient-text">{{ total() | money: auth.currency() }}</div></div>
          <span class="badge badge-primary">{{ 'common.transactions' | t: { n: expenses().length } }}</span>
        </div>
        <div class="filters">
          <div class="search">
            <span>🔎</span>
            <input class="input" [placeholder]="'expenses.search' | t" [ngModel]="search()" (ngModelChange)="search$.next($event)" />
          </div>
          <select class="input cat-filter" [ngModel]="categoryId()" (ngModelChange)="categoryId.set($event)">
            <option [ngValue]="null">{{ 'expenses.allCategories' | t }}</option>
            @for (c of categories(); track c.id) { <option [ngValue]="c.id">{{ c.icon }} {{ c.name | cat }}</option> }
          </select>
        </div>

        @if (loading()) {
          <div class="loading-box"><span class="spinner lg"></span></div>
        } @else if (expenses().length) {
          <div class="table-wrap">
            <table class="table table-cards">
              <thead>
                <tr><th>{{ 'web.table.expense' | t }}</th><th>{{ 'common.category' | t }}</th><th>{{ 'common.date' | t }}</th><th class="hide-mobile">{{ 'web.table.method' | t }}</th><th class="text-right">{{ 'web.table.amount' | t }}</th><th></th></tr>
              </thead>
              <tbody>
                @for (e of expenses(); track e.id) {
                  <tr [class.flash]="flashId() === e.id">
                    <td class="cell-main"><b>{{ e.description }}</b></td>
                    <td class="cell-meta"><span class="cat-chip"><span class="cat-dot" [style.background]="e.category.color + '22'" [style.border-color]="e.category.color + '55'">{{ e.category.icon }}</span>{{ e.category.name | cat }}</span></td>
                    <td class="nowrap muted cell-meta">{{ e.date | date2: 'weekday' }}</td>
                    <td class="hide-mobile"><span class="badge">{{ methodIcon(e.paymentMethod) }} {{ 'pm.' + e.paymentMethod | t }}</span></td>
                    <td class="text-right nowrap num cell-amount"><b>{{ e.amount | money: auth.currency() }}</b></td>
                    <td class="actions">
                      <button class="icon-btn" [title]="'common.edit' | t" (click)="openForm(e)">✏️</button>
                      <button class="icon-btn danger" [title]="'common.delete' | t" (click)="toDelete.set(e)">🗑️</button>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        } @else {
          <div class="empty-state">
            <div class="emoji">🧾</div>
            <h4>{{ 'expenses.noneFound' | t }}</h4>
            <p>{{ (search() || categoryId() ? 'expenses.tryFilter' : 'expenses.addFirst') | t }}</p>
          </div>
        }
      </div>
    </div>

    @if (formOpen()) {
      <app-expense-form [expense]="editing()" [month]="month()" (closed)="formOpen.set(false)" (saved)="flash($event.id)" />
    }
    @if (toDelete(); as e) {
      <app-confirm [title]="'expenses.deleteTitle' | t" [message]="'expenses.deleteMsg' | t: { name: e.description }" [confirmLabel]="'common.delete' | t"
                   (confirm)="remove(e)" (cancel)="toDelete.set(null)" />
    }
  `,
  styles: [`
    .total-strip { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin-bottom: 18px; flex-wrap: wrap; }
    .total { font-size: 30px; font-weight: 700; letter-spacing: -.03em; margin-top: 2px; }
    @media (max-width: 760px) { .cat-filter { width: 100%; } .header-actions { width: 100%; } }
    .filters { display: flex; gap: 12px; margin-bottom: 18px; flex-wrap: wrap; }
    .search { flex: 1; min-width: 220px; position: relative; }
    .search span { position: absolute; inset-inline-start: 12px; top: 50%; transform: translateY(-50%); font-size: 14px; }
    .search .input { padding-inline-start: 36px; }
    .cat-filter { width: 230px; }
    tr.flash { animation: flash 1.6s ease; }
    @keyframes flash { 0%, 40% { background: var(--primary-soft); } }
  `],
})
export class ExpensesComponent {
  private api = inject(ApiService);
  private toast = inject(ToastService);
  private realtime = inject(RealtimeService);
  readonly auth = inject(AuthService);

  readonly month = signal(Months.current());
  readonly search = signal('');
  readonly search$ = new Subject<string>();
  readonly categoryId = signal<number | null>(null);
  readonly expenses = signal<Expense[]>([]);
  readonly categories = signal<Category[]>([]);
  readonly loading = signal(true);
  readonly formOpen = signal(false);
  readonly editing = signal<Expense | null>(null);
  readonly toDelete = signal<Expense | null>(null);
  readonly flashId = signal<number | null>(null);

  readonly total = computed(() => this.expenses().reduce((s, e) => s + e.amount, 0));
  private i18n = inject(I18nService);
  readonly monthLabel = computed(() => {
    this.i18n.lang();
    return Months.label(this.month());
  });

  constructor() {
    this.api.categories().subscribe((c) => this.categories.set(c));
    this.search$.pipe(debounceTime(250), takeUntilDestroyed()).subscribe((q) => this.search.set(q));

    effect(() => {
      this.month();
      this.search();
      this.categoryId();
      untracked(() => this.load(true));
    });

    this.realtime.on('EXPENSES_CHANGED', 'CATEGORIES_CHANGED').pipe(debounceTime(200), takeUntilDestroyed()).subscribe((e) => {
      this.load(false);
      if (e.type === 'CATEGORIES_CHANGED') this.api.categories().subscribe((c) => this.categories.set(c));
      if (e.payload?.id) this.flash(e.payload.id);
    });
  }

  load(showSpinner: boolean) {
    if (showSpinner) this.loading.set(true);
    this.api.expenses(this.month(), this.categoryId(), this.search()).subscribe({
      next: (list) => {
        this.expenses.set(list);
        this.loading.set(false);
      },
      error: () => this.loading.set(false),
    });
  }

  openForm(e: Expense | null) {
    this.editing.set(e);
    this.formOpen.set(true);
  }

  flash(id: number) {
    this.flashId.set(id);
    setTimeout(() => this.flashId.set(null), 1600);
  }

  remove(e: Expense) {
    this.toDelete.set(null);
    this.api.deleteExpense(e.id).subscribe({
      next: () => {
        this.expenses.update((l) => l.filter((x) => x.id !== e.id));
        this.toast.success(t('expenses.deleted'));
      },
      error: (err) => this.toast.error(t('common.couldNotDelete'), errorMessage(err)),
    });
  }

  methodIcon(m: string) {
    return PAYMENT_METHODS.find((p) => p.value === m)?.icon ?? '';
  }

  exportCsv() {
    const rows = [tList('expenses.csvHeaders')];
    for (const e of this.expenses()) {
      rows.push([e.date, e.description, catName(e.category.name), t(`pm.${e.paymentMethod}`), e.amount.toFixed(2), this.auth.currency()]);
    }
    const csv = rows.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8' });
    downloadBlob(blob, `expenses-${this.month()}.csv`);
  }
}

// mobile/src/app/(tabs)/expenses.tsx
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { errorMessage } from '@/api/client';
import { api } from '@/api/endpoints';
import { shareText } from '@/api/files';
import { Expense, PAYMENT_METHODS } from '@/api/models';
import { qk } from '@/api/queryKeys';
import { useAuth } from '@/auth/AuthContext';
import { MonthPicker } from '@/components/MonthPicker';
import { useToast } from '@/components/Toast';
import {
  Badge, Button, Card, CategoryDot, Chip, confirm, EmptyState, IconButton, Input, Loading, Notice, PageHeader, Row, Screen, Txt,
} from '@/components/ui';
import { catName, t, tList, useI18n } from '@/i18n';
import { fonts, useTheme } from '@/theme/theme';
import { formatDate, formatMoney, Months } from '@/utils/format';

export default function ExpensesScreen() {
  const { currency } = useAuth();
  const { colors } = useTheme();
  useI18n();
  const toast = useToast();
  const queryClient = useQueryClient();
  const [month, setMonth] = useState(Months.current());
  const [searchDraft, setSearchDraft] = useState('');
  const [search, setSearch] = useState('');
  const [categoryId, setCategoryId] = useState<number | null>(null);

  // Debounce the search box like the web app.
  useEffect(() => {
    const timer = setTimeout(() => setSearch(searchDraft.trim()), 300);
    return () => clearTimeout(timer);
  }, [searchDraft]);

  const categories = useQuery({ queryKey: qk.categories, queryFn: api.categories });
  const expenses = useQuery({
    queryKey: qk.expenses(month, categoryId, search),
    queryFn: () => api.expenses(month, categoryId, search),
    placeholderData: (prev) => prev,
  });

  const list = expenses.data ?? [];
  const total = list.reduce((s, e) => s + e.amount, 0);
  const money = (v: number) => formatMoney(v, currency);

  const edit = (e: Expense) => router.push({ pathname: '/expense-form', params: { expense: JSON.stringify(e) } });

  const remove = (e: Expense) =>
    confirm(t('expenses.deleteTitle'), t('expenses.deleteMsg', { name: e.description }), async () => {
      try {
        await api.deleteExpense(e.id);
        toast.success(t('expenses.deleted'));
        for (const key of ['expenses', 'dashboard', 'budgets', 'goals']) queryClient.invalidateQueries({ queryKey: [key] });
      } catch (err) {
        toast.error(t('common.couldNotDelete'), errorMessage(err));
      }
    });

  const exportCsv = async () => {
    const rows: (string | number)[][] = [tList('expenses.csvHeaders')];
    for (const e of list) rows.push([e.date, e.description, catName(e.category.name), t(`pm.${e.paymentMethod}`), e.amount.toFixed(2), currency]);
    const csv = rows.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n');
    try {
      await shareText(`expenses-${month}.csv`, '﻿' + csv, 'text/csv', 'public.comma-separated-values-text');
    } catch (err) {
      toast.error(t('expenses.exportError'), errorMessage(err));
    }
  };

  return (
    <Screen onRefresh={() => expenses.refetch()} refreshing={expenses.isRefetching}>
      <PageHeader
        title={t('expenses.title')}
        subtitle={t('expenses.subtitle')}
        right={<Button title="CSV" icon="⬇" variant="ghost" size="sm" onPress={exportCsv} disabled={!list.length} />}
      />
      <MonthPicker month={month} onChange={setMonth} />

      <Card>
        <Row style={{ justifyContent: 'space-between' }}>
          <View style={{ flexShrink: 1 }}>
            <Txt variant="eyebrow">{t('expenses.spentIn', { month: Months.label(month) })}</Txt>
            <Txt variant="h1" color={colors.primaryText} style={{ marginTop: 2 }}>{money(total)}</Txt>
          </View>
          <Badge label={t('common.transactions', { n: list.length })} tone="primary" />
        </Row>
      </Card>

      <Input value={searchDraft} onChangeText={setSearchDraft} placeholder={t('expenses.search')} clearButtonMode="while-editing" autoCorrect={false} />
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginTop: -8, marginHorizontal: -16 }} contentContainerStyle={{ gap: 7, paddingHorizontal: 16 }}>
        <Chip label={t('expenses.allCategories')} selected={categoryId === null} onPress={() => setCategoryId(null)} />
        {(categories.data ?? []).map((c) => (
          <Chip key={c.id} label={catName(c.name)} icon={c.icon} color={c.color} selected={categoryId === c.id} onPress={() => setCategoryId(c.id)} />
        ))}
      </ScrollView>

      {expenses.isError ? <Notice tone="danger" text={errorMessage(expenses.error)} /> : null}
      {expenses.isLoading ? (
        <Loading />
      ) : list.length ? (
        <Card style={{ paddingVertical: 6, paddingHorizontal: 10 }}>
          {list.map((e, i) => (
            <Pressable
              key={e.id}
              onPress={() => edit(e)}
              onLongPress={() => remove(e)}
              style={({ pressed }) => ({
                flexDirection: 'row',
                alignItems: 'center',
                gap: 12,
                paddingVertical: 12,
                paddingHorizontal: 4,
                borderTopWidth: i ? 1 : 0,
                borderColor: colors.border,
                opacity: pressed ? 0.7 : 1,
              })}
            >
              <CategoryDot icon={e.category.icon} color={e.category.color} />
              <View style={{ flex: 1, gap: 2 }}>
                <Txt numberOfLines={1} style={{ fontFamily: fonts.semibold }}>{e.description}</Txt>
                <Txt variant="dim" numberOfLines={1}>
                  {catName(e.category.name)} · {formatDate(e.date)} · {PAYMENT_METHODS.find((m) => m.value === e.paymentMethod)?.icon ?? ''}{' '}
                  {t(`pm.${e.paymentMethod}`)}
                </Txt>
              </View>
              <Text style={{ color: colors.text, fontFamily: fonts.display, fontSize: 14 }}>{money(e.amount)}</Text>
              <IconButton icon="🗑️" label={t('common.delete')} tone="danger" onPress={() => remove(e)} />
            </Pressable>
          ))}
        </Card>
      ) : (
        <Card>
          <EmptyState
            emoji="🧾"
            title={t('expenses.noneFound')}
            text={search || categoryId ? t('expenses.tryFilter') : t('expenses.addFirst')}
            action={<Button title={t('expenses.add')} icon="＋" size="sm" onPress={() => router.push({ pathname: '/expense-form', params: { month } })} />}
          />
        </Card>
      )}
      {list.length ? <Txt variant="dim" style={{ textAlign: 'center' }}>{t('common.tapToEdit')}</Txt> : null}
    </Screen>
  );
}
