// mobile/src/app/expense-form.tsx
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { router, Stack, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, View } from 'react-native';
import { errorMessage } from '@/api/client';
import { api } from '@/api/endpoints';
import { Expense, PAYMENT_METHODS, PaymentMethod } from '@/api/models';
import { qk } from '@/api/queryKeys';
import { useAuth } from '@/auth/AuthContext';
import { DateField } from '@/components/DateField';
import { useToast } from '@/components/Toast';
import { Button, Chip, confirm, Input, Loading, Notice, Txt } from '@/components/ui';
import { catName, t, useI18n } from '@/i18n';
import { fonts, useTheme } from '@/theme/theme';
import { Months } from '@/utils/format';
import { haptics } from '@/utils/haptics';
import { useJsonParam } from '@/utils/params';

export default function ExpenseFormScreen() {
  const expense = useJsonParam<Expense>('expense');
  const { month } = useLocalSearchParams<{ month?: string }>();
  const { currency } = useAuth();
  const { colors } = useTheme();
  useI18n();
  const toast = useToast();
  const queryClient = useQueryClient();
  const categories = useQuery({ queryKey: qk.categories, queryFn: api.categories });

  const [amount, setAmount] = useState(expense ? String(expense.amount) : '');
  const [categoryId, setCategoryId] = useState<number | null>(expense?.category.id ?? null);
  const [description, setDescription] = useState(expense?.description ?? '');
  const [date, setDate] = useState(expense?.date ?? Months.defaultDate(month ?? Months.current()));
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>(expense?.paymentMethod ?? 'CARD');
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const value = Number(amount.replace(',', '.'));
  const errors = {
    amount: !(value > 0) ? t('expenses.amountError') : '',
    categoryId: categoryId === null ? t('expenses.categoryError') : '',
    description: !description.trim() ? t('expenses.descriptionError') : '',
  };

  const invalidate = () => {
    for (const key of ['expenses', 'dashboard', 'budgets', 'goals']) queryClient.invalidateQueries({ queryKey: [key] });
  };

  const submit = async () => {
    setSubmitted(true);
    if (Object.values(errors).some(Boolean) || saving) return;
    setSaving(true);
    setError('');
    const body = { amount: Math.round(value * 100) / 100, categoryId: categoryId!, description: description.trim(), date, paymentMethod };
    try {
      const saved = expense ? await api.updateExpense(expense.id, body) : await api.createExpense(body);
      haptics.success();
      toast.success(expense ? t('expenses.updated') : t('expenses.added'), `${saved.category.icon} ${saved.description}`);
      invalidate();
      router.back();
    } catch (err) {
      setError(errorMessage(err));
      setSaving(false);
    }
  };

  const remove = () =>
    expense &&
    confirm(t('expenses.deleteTitle'), t('expenses.deleteMsg', { name: expense.description }), async () => {
      try {
        await api.deleteExpense(expense.id);
        toast.success(t('expenses.deleted'));
        invalidate();
        router.back();
      } catch (err) {
        toast.error(t('common.couldNotDelete'), errorMessage(err));
      }
    });

  return (
    <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1, backgroundColor: colors.bg }}>
      <Stack.Screen options={{ title: expense ? t('expenses.editTitle') : t('expenses.newTitle') }} />
      <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }} keyboardShouldPersistTaps="handled">
        {error ? <View style={{ marginBottom: 12 }}><Notice tone="danger" text={error} /></View> : null}

        <Input
          label={t('common.amountIn', { cur: currency })}
          value={amount}
          onChangeText={setAmount}
          placeholder="0.00"
          keyboardType="decimal-pad"
          autoFocus={!expense}
          error={submitted && errors.amount}
          style={{ fontFamily: fonts.display, fontSize: 30, textAlign: 'center', paddingVertical: 14 }}
        />

        <Txt variant="label" style={{ marginBottom: 8 }}>{t('common.category')}</Txt>
        {categories.isLoading ? (
          <Loading />
        ) : (
          <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 6 }}>
            {(categories.data ?? []).map((c) => (
              <Chip key={c.id} label={catName(c.name)} icon={c.icon} color={c.color} selected={categoryId === c.id} onPress={() => setCategoryId(c.id)} />
            ))}
          </View>
        )}
        {submitted && errors.categoryId ? <Txt variant="small" color={colors.danger}>{errors.categoryId}</Txt> : null}
        <View style={{ height: 12 }} />

        <Input
          label={t('common.description')}
          value={description}
          onChangeText={setDescription}
          placeholder={t('expenses.descPlaceholder')}
          maxLength={200}
          error={submitted && errors.description}
          returnKeyType="done"
        />

        <DateField label={t('common.date')} value={date} onChange={setDate} />

        <Txt variant="label" style={{ marginBottom: 8 }}>{t('expenses.paymentMethod')}</Txt>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 24 }}>
          {PAYMENT_METHODS.map((m) => (
            <Chip key={m.value} label={t(`pm.${m.value}`)} icon={m.icon} selected={paymentMethod === m.value} onPress={() => setPaymentMethod(m.value)} />
          ))}
        </View>

        <Button title={expense ? t('expenses.saveChanges') : t('expenses.add')} size="lg" onPress={submit} loading={saving} />
        {expense ? <Button title={t('expenses.deleteBtn')} variant="ghost" onPress={remove} style={{ marginTop: 10 }} /> : null}
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

// frontend/src/app/shared/expense-form.component.ts
import { Component, inject, input, OnInit, output, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { errorMessage } from '../core/auth.interceptor';
import { AuthService } from '../core/auth.service';
import { CategoryNamePipe, t, TranslatePipe } from '../core/i18n';
import { Category, Expense, PAYMENT_METHODS } from '../core/models';
import { Months, ToastService } from '../core/ui.service';
import { ModalComponent } from './modal.component';
import { Native } from '../core/native';

@Component({
  selector: 'app-expense-form',
  imports: [ReactiveFormsModule, ModalComponent, TranslatePipe, CategoryNamePipe],
  template: `
    <app-modal [title]="(expense() ? 'expenses.editTitle' : 'expenses.newTitle') | t" (closed)="closed.emit()">
      <form [formGroup]="form" (ngSubmit)="submit()">
        @if (error()) { <div class="alert alert-error">{{ error() }}</div> }

        <div class="form-field">
          <label for="amount">{{ 'common.amountIn' | t: { cur: auth.currency() } }}</label>
          <input id="amount" class="input amount-input" type="number" step="0.01" min="0.01" formControlName="amount" placeholder="0.00" autofocus
                 [class.invalid]="invalid('amount')" />
          @if (invalid('amount')) { <span class="field-error">{{ 'expenses.amountError' | t }}</span> }
        </div>

        <div class="form-field">
          <label>{{ 'common.category' | t }}</label>
          <div class="cat-grid">
            @for (c of categories(); track c.id) {
              <button type="button" class="cat-option" [class.selected]="form.value.categoryId === c.id"
                      [style.--c]="c.color" (click)="form.patchValue({ categoryId: c.id })">
                <span>{{ c.icon }}</span>{{ c.name | cat }}
              </button>
            }
          </div>
          @if (invalid('categoryId')) { <span class="field-error">{{ 'expenses.categoryError' | t }}</span> }
        </div>

        <div class="form-field">
          <label for="description">{{ 'common.description' | t }}</label>
          <input id="description" class="input" formControlName="description" [placeholder]="'expenses.descPlaceholder' | t" maxlength="200"
                 [class.invalid]="invalid('description')" />
          @if (invalid('description')) { <span class="field-error">{{ 'expenses.descriptionError' | t }}</span> }
        </div>

        <div class="form-row">
          <div class="form-field">
            <label for="date">{{ 'common.date' | t }}</label>
            <input id="date" class="input" type="date" formControlName="date" [max]="today" />
          </div>
          <div class="form-field">
            <label for="method">{{ 'expenses.paymentMethod' | t }}</label>
            <select id="method" class="input" formControlName="paymentMethod">
              @for (m of methods; track m.value) { <option [value]="m.value">{{ 'pm.' + m.value | t }}</option> }
            </select>
          </div>
        </div>

        <div class="modal-actions">
          <button type="button" class="btn btn-ghost" (click)="closed.emit()">{{ 'common.cancel' | t }}</button>
          <button type="submit" class="btn btn-primary" [disabled]="saving()">
            @if (saving()) { <span class="spinner"></span> } {{ (expense() ? 'expenses.saveChanges' : 'expenses.add') | t }}
          </button>
        </div>
      </form>
    </app-modal>
  `,
  styles: [`
    .amount-input { height: 64px; font-family: var(--font-display); font-size: 30px; font-weight: 700; text-align: center; letter-spacing: -.02em; }
    .cat-grid { display: flex; flex-wrap: wrap; gap: 7px; max-height: 170px; overflow-y: auto; padding: 2px; }
    .cat-option { display: inline-flex; align-items: center; gap: 6px; border: 1px solid var(--border); background: var(--surface-2); color: var(--text);
      border-radius: 999px; padding: 6px 12px; font: inherit; font-size: 13px; cursor: pointer; transition: all .12s; }
    .cat-option:hover { border-color: var(--c); }
    .cat-option.selected { border-color: var(--c); background: color-mix(in srgb, var(--c) 18%, transparent); font-weight: 600; box-shadow: 0 0 0 1px var(--c), 0 0 16px color-mix(in srgb, var(--c) 50%, transparent); }
  `],
})
export class ExpenseFormComponent implements OnInit {
  readonly expense = input<Expense | null>(null);
  readonly month = input<string>(Months.current());
  readonly closed = output<void>();
  readonly saved = output<Expense>();

  readonly auth = inject(AuthService);
  private api = inject(ApiService);
  private toast = inject(ToastService);
  private fb = inject(FormBuilder);

  readonly methods = PAYMENT_METHODS;
  readonly today = Months.today();
  readonly categories = signal<Category[]>([]);
  readonly saving = signal(false);
  readonly error = signal('');
  submitted = false;

  readonly form = this.fb.nonNullable.group({
    amount: [null as number | null, [Validators.required, Validators.min(0.01)]],
    categoryId: [null as number | null, Validators.required],
    description: ['', [Validators.required, Validators.maxLength(200)]],
    date: [Months.today(), Validators.required],
    paymentMethod: ['CARD', Validators.required],
  });

  ngOnInit() {
    this.api.categories().subscribe((c) => this.categories.set(c));
    const e = this.expense();
    if (e) {
      this.form.patchValue({ amount: e.amount, categoryId: e.category.id, description: e.description, date: e.date, paymentMethod: e.paymentMethod });
    } else {
      this.form.patchValue({ date: Months.defaultDate(this.month()) });
    }
  }

  invalid(name: string) {
    const c = this.form.get(name);
    return !!c && c.invalid && (c.touched || this.submitted);
  }

  submit() {
    this.submitted = true;
    if (this.form.invalid) return;
    this.saving.set(true);
    this.error.set('');
    const v = this.form.getRawValue();
    const body = { amount: Number(v.amount), categoryId: v.categoryId!, description: v.description, date: v.date, paymentMethod: v.paymentMethod as any };
    const e = this.expense();
    const req = e ? this.api.updateExpense(e.id, body) : this.api.createExpense(body);
    req.subscribe({
      next: (saved) => {
        this.toast.success(t(e ? 'expenses.updated' : 'expenses.added'), `${saved.category.icon} ${saved.description}`);
        Native.success();
        this.saved.emit(saved);
        this.closed.emit();
      },
      error: (err) => {
        this.error.set(errorMessage(err));
        this.saving.set(false);
      },
    });
  }
}
